models/Alumnos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "alumnos".
 *
 * @property int $id
 * @property string $nombre
 * @property string $apellidos
 * @property string $dni
 * @property string $direccion
 * @property string $poblacion
 * @property int $movil
 * @property int $fijo
 * @property string $email
 * @property string $alta
 * @property string $curso
 * @property string $centro
 * @property string $observaciones
 *
 * @property Agrupan[] $agrupans
 * @property CuentasBancarias[] $cuentasBancarias
 * @property Matriculas[] $matriculas
 */
class Alumnos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'alumnos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['movil', 'fijo'], 'integer'],
            [['alta'], 'safe'],
            //[['alta'], 'date', 'format' => 'php:Y-m-d'],
            [['observaciones'], 'string'],
            [['nombre', 'poblacion', 'centro'], 'string', 'max' => 100],
            [['apellidos', 'direccion', 'email'], 'string', 'max' => 200],
            [['dni'], 'string', 'max' => 9],
            [['curso'], 'string', 'max' => 50],
            [['pago'], 'string','max' => 50],
            [['dni'], 'unique']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'apellidos' => 'Apellidos',
            'dni' => 'Dni',
            'direccion' => 'Direccion',
            'poblacion' => 'Poblacion',
            'movil' => 'Movil',
            'fijo' => 'Fijo',
            'email' => 'Email',
            'alta' => 'Alta',
            'curso' => 'Curso',
            'centro' => 'Centro',
            'pago' => 'Pago',
            'observaciones' => 'Observaciones',
        ];  
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgrupans()
    {
        return $this->hasMany(Agrupan::className(), ['alumno' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCuentasBancarias()
    {
        return $this->hasMany(CuentasBancarias::className(), ['alumno' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMatriculas(){
        return $this->hasMany(Matriculas::className(), ['alumno' => 'id']);
    }
    
    public function afterFind() {
        parent::afterFind();
        $this->alta=Yii::$app->formatter->asDate($this->alta, 'php:d-m-Y');;
        
    }

    
    public function beforeSave($insert) {
          parent::beforeSave($insert);
          $this->alta=Yii::$app->formatter->asDate($this->alta, 'php:Y-m-d');
          //$this->alta= \DateTime::createFromFormat("d/m/Y", $this->alta)->format("Y/m/d");
          return true;
    }

}

controllers/AlumnosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Alumnos;
use app\models\AlumnosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\SqlDataProvider;

/**
 * AlumnosController implements the CRUD actions for Alumnos model.
 */
class AlumnosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Alumnos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AlumnosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Alumnos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Alumnos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Alumnos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Alumnos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Alumnos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionDuplicar($alumno){
       
    //creamos la consulta con los registros que generan los recibos

        $dataProvider = new SqlDataProvider([
            'sql' => "SELECT * from alumnos where id ='$alumno'",        
        ]);


    // bucle que va insertando los registros en recibos con los criterios de seleccion y los emitidos a traves del formulario

        $resultado = $dataProvider->getModels();
      

        foreach ($resultado as $value) {
                $model = new Alumnos();
                $model->apellidos = $value['apellidos'];
                $model->direccion = $value['direccion'];
                $model->poblacion = $value['poblacion'];
                $model->movil = $value['movil'];
                $model->fijo = $value['fijo'];
                $model->email = $value['email'];
                $model->alta = "";
                $model->save();
        }
         return $this->redirect(['index']);
               
    }            
    
    /**
     * Finds the Alumnos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Alumnos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Alumnos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/alumnos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\datepicker\DatePicker;
use yii\helpers\ArrayHelper;
use app\models\Centros;
use app\models\Cursos;

/* @var $this yii\web\View */
/* @var $model app\models\Alumnos */
/* @var $form yii\widgets\ActiveForm */

$ListCentros = ArrayHelper::map(Centros::find()->all(), 'id', 'nombre');
$listaCursos = ArrayHelper::map(Cursos::find()->all(), 'id', 'curso');
$formasPago = [1 => 'Efectivo', 2 => 'Transferencia']; 
?>

<div class="alumnos-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'apellidos')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'dni')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'direccion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'poblacion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'movil')->textInput() ?>

    <?= $form->field($model, 'fijo')->textInput() ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

     <!--$form->field($model, 'alta')->textInput()-->
     <!--$form->field($model,'alta')->widget(DatePicker::className(),['clientOptions' => ['dateFormat' => 'd-m-yyyy']]) ?>-->
    <?= $form->field($model, 'alta')->widget(DatePicker::className(), [
            // inline too, not bad
            'inline' => false, 
             // modify template for custom rendering
            //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
            'clientOptions' => [
            'autoclose' => true,
            'format' => 'dd-mm-yyyy',
            'todayBtn' => true
            ]
    ]);?>

     
    <?= $form->field($model, 'curso')->dropDownList($listaCursos, ['prompt' => 'Seleccione Uno' ],['maxlength'=>true]); ?>
    <?= $form->field($model, 'centro')->dropDownList($ListCentros, ['prompt' => 'Seleccione Uno' ]); ?>
    <?= $form->field($model, 'pago')->dropDownList($formasPago, ['prompt' => 'Seleccione Uno' ]); ?>
    <?= $form->field($model, 'observaciones')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
       
    </div>
    
       
    
    <?php ActiveForm::end(); ?>

</div>

views/alumnos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AlumnosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="alumnos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'apellidos') ?>

    <?= $form->field($model, 'dni') ?>

    <?= $form->field($model, 'direccion') ?>

    <?php // echo $form->field($model, 'poblacion') ?>

    <?php // echo $form->field($model, 'movil') ?>

    <?php // echo $form->field($model, 'fijo') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'alta') ?>

    <?php // echo $form->field($model, 'curso') ?>

    <?php // echo $form->field($model, 'centro') ?>

    <?php // echo $form->field($model, 'observaciones') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/alumnos/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Alumnos */

$this->title = 'Crear Alumnos';
$this->params['breadcrumbs'][] = ['label' => 'Alumnos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="alumnos-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/alumnos/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AlumnosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Alumnos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="alumnos-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Crear Alumnos', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'nombre',
            'apellidos',
            'dni',
            'direccion',
            //'poblacion',
            //'movil',
            //'fijo',
            //'email:email',
            //'alta',
            //'curso',
            //'centro',
            //'observaciones:ntext',

            ['class' => 'yii\grid\ActionColumn',
                 'contentOptions'=>['style'=>'width: 70px;'],
                
            ],
            
               [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{agrupaciones}',
                'contentOptions'=>['style'=>'width: 30px;'],
                'buttons' => [
                'agrupaciones' => function ($url, $model) {
                                    return Html::a('<span class="glyphicon glyphicon-user"></span>', $url, [
                                        'title' => Yii::t('app', 'Agrupan'),
                                    ]);

                                }, 
                                
                ],
                        
                'urlCreator' => function ($action, $model, $key, $index) {
                     return Url::to(['agrupan/index', 'id' => $model->id,'nombre'=>$model->nombre,'apellidos'=>$model->apellidos]);
                }        
                 
            ],    
            [
              'class' => 'yii\grid\ActionColumn',
              'template' => '{matriculas}',
              'contentOptions'=>['style'=>'width: 40px;'],
              'buttons' => [
              'matriculas' => function ($url, $model) {
                                  return Html::a('<span class="glyphicon glyphicon-bookmark"></span>', $url, [
                                      'title' => Yii::t('app', 'Matriculas'),
                                  ]);

                              }, 

                             ],

              'urlCreator' => function ($action, $model, $key, $index) {
                   return Url::to(['matriculas/matriculas_alumno', 'alumno' => $model->id,'nombre'=>$model->nombre,'apellidos'=>$model->apellidos]);
              }        

            ],          
            [
              'class' => 'yii\grid\ActionColumn',
              'template' => '{duplicados}',
              'contentOptions'=>['style'=>'width: 40px;'],
              'buttons' => [
              'duplicados' => function ($url, $model) {
                                  return Html::a('<span class="glyphicon glyphicon-duplicate"></span>', $url, [
                                      'title' => Yii::t('app', 'Duplicar Alumno'),
                                  ]);

                              }, 

                             ],

              'urlCreator' => function ($action, $model, $key, $index) {
                   return Url::to(['alumnos/duplicar', 'alumno' => $model->id]);
              }        

            ],          
            
            
 
        ],
    ]); ?>


</div>

views/alumnos/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Alumnos */

$this->title = 'Actualizar Alumno: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Alumnos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="alumnos-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/alumnos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Alumnos */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Alumnos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="alumnos-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'apellidos',
            'dni',
            'direccion',
            'poblacion',
            'movil',
            'fijo',
            'email:email',
            'alta',
            'curso',
            'centro',
            'pago',
            'observaciones:ntext',
        ],
    ]) ?>

</div>